# Generated by Django 3.1.2 on 2020-11-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_list',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
