# Generated by Django 3.1.2 on 2020-11-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201105_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
